### ISSUE TITLE
Product discovery plan

### ISSUE THREAD

**Issue by menduz** [decentraland/editor-sdk6#1]
# Phase 0 - Product discovery

The objective of this phase is to get used to the new technologies (vscode extension) and the publication flows. It will be done via implementing some basic functionalities on top of the CLI of Decentraland

- [x] Research how to create and publish VSCode extensions, set up CI
- [x] Create example extension that runs a Decentraland Preview of the current opened folder inside VSCode:
  - [x] Compile a and preview a Decentraland project without using the command line
  - [x] Create a new Decentraland Project from a template
  - [x] Automatically install the NPM dependencies for a Decentraland project
  - [x] Deploy a scene from VSCode

# Phase 1.0 - Initial implementation
- [ ] Come up with an architecture plan that scales taking into account CLI/standalone tooling (ToolingServer library)
- [ ] Initial implementation of the ToolingServer library. Its responsibilities for this phase are:
  - [ ] Support multiple projects in the VSCode workspace, have a single instance of ToolingServer for all projects
  - [ ] On-demand compilation of these projects using `@dcl/build-ecs` lib
  - [ ] On-demand "compile and watch" of these projects using `@dcl/build-ecs` lib, emiting events of each project when they fail or succeed
  - [ ] Expose a WebSocket RPC connection for Kernel, to send the updates about which scenes should be reloaded and to send information of Kernel, renderer and scenes back to the Extension
  - [ ] Expose a WebSocket or IPC RPC connection to communicate with the Extension
- [ ] "Preview" a project or workspace using ToolingServer and new Preview. 
- [ ] Show in VSCode information about the scenes running in Kernel in a sidebar

# Phase 1.1 - Enhance the developers' experience
The objective of this phase is to polish and allow all the paths done via the CLI via web interface.
- [x] `dcl init` flow
- [x] `dcl build` flow
- [x] `dcl start` flow
- [x] `dcl deploy` flow 
- [ ] Allow multiple renderer versions

# Phase 1.2 - Debugging
The objective of this phase is to introduce a debugger for a scene inside VSCode
- [ ] Create NodeScene and connect it to Kernel for preview mode. This scene runs inside or controlled by the ToolingServer
- [ ] Hot-reload the scene keeping the same connection. It should be controlled by ToolingServer and upon hot-reload it should send a message to delete all entities and state from renderers. This will later be used to hot-reload the code of a scene keeping the state
- [ ] Intercept in/out CRDT messages of that scene to create the entity inspector in the extension
- [ ] Connect a VSCode JS debugger to node's debugger protocol to play/pause/manage breakpoints in the scene

# Phase 2.0 - Improve art and development pipelines
The objective of this phase is to introduce Artists to the production pipeline of a scene. Enabling them to position things in world and previewing them.
- [ ] Define format to describe prefabs. It should be nice with git diff/patch and human readable
- [ ] Create prefab loaders for the SDK
- [ ] Create play mode and design mode for preview. Prefabs can be previewed in Design mode
- [ ] Create Prefab->CRDT conversor for runtime
- [ ] Create entity tree visualizer for selected prefab in design mode
- [ ] Create entity & components editor for selected entity (must enable Undo/Redo)
- [ ] Enable drag&drop entities in the tree (must enable Undo/Redo)
- [ ] Enable creation/deletion of prefabs via UI button

# Phase 3.0 - Interactive scenes without code
TBD
